components: Improve channel icon styles in cards
endlessm/kolibri-explore-plugin pull request #188
Opened 2021-07-13 11:30 UTC by danigm

Use h6 for the channel title so it has the same font and sizes than
other titles in cards.

https://phabricator.endlessm.com/T32067

2021-07-13 21:31 UTC, manuq requested changes

2021-07-13 21:31 UTC, manuq commented on packages/eos-components/src/components/CardBody.vue
> +      <h6 class="align-items-center d-flex mb-1 text-muted">
Should be mb-3 (16px) as Joana said.

The h6 doesn't have the text size requested. The easiest is to add the "btn" class. But that also adds unwanted padding. So it has to be done adding a custom class and then:

```
.channel-title {
  font-family: $btn-font-family;
  font-size: $btn-font-size;
  font-weight: $btn-font-weight;
}
```

2021-07-13 23:08 UTC, manuq commented
I implemented this using another approach in https://github.com/endlessm/kolibri-explore-plugin/pull/188#pullrequestreview-705664377

2021-07-14 07:20 UTC, danigm commented
This change is superseded by #192

2021-07-14 07:20 UTC, closed without merging