Components: Add description to CarouselCard
endlessm/kolibri-explore-plugin pull request #252
Opened 2021-08-05 10:49 UTC by danigm

Adds the description to the CarouselCard if exists and in that case the
title will have just one line.

If there's no description the behavior is the same as before.

https://phabricator.endlessm.com/T32345

2021-08-05 11:13 UTC, manuq reviewed
Code-wise looks good. I commented in the ticket.

2021-08-05 11:34 UTC, manuq requested changes
I know Joana said "max width" but I think we should let the components allocate the desired size.

2021-08-05 11:34 UTC, manuq commented on packages/eos-components/src/components/CarouselCard.vue
> +  max-width: calc(100% - 100px);
I guess we can use a flexbox to do this properly and avoid hardcoding the button size, which will change depending on the text label. Think if in the future we support translations.

2021-08-10 11:13 UTC, danigm commented
Closing this, we don't need the description for now.

2021-08-10 11:13 UTC, closed without merging