Bring back filters with new API call
endlessm/kolibri-explore-plugin pull request #278
Opened 2021-09-20 15:12 UTC by danigm

This patch bring back filters (currently just the media type one) using
the kolibri.getContentByFilter new API.

https://phabricator.endlessm.com/T32510

This patch uses the new API option implemented here:

2021-09-27 22:00 UTC, manuq requested changes
When testing this with the Dance channel the filter component is not shown. I'm getting: `TypeError: Cannot use 'in' operator to search for 'audio' in undefined`.

For this channel I expect to have a filter for the multiple authors.

Also, from the code I don't understand if you are trying to make the structured tags work, or if you are only moving the old code around. I suggest that we drop that functionality and care only about the current metadata at this stage.

![Captura de pantalla de 2021-09-27 18-56-59](https://user-images.githubusercontent.com/83944/134991132-94a890c2-51bd-4103-9465-f65ed62b52e7.png)

2021-09-27 22:00 UTC, manuq commented on packages/template-ui/src/App.vue
> +      return Promise.all([channelPromise, filterOptionsPromise]);
Only fetch the filter options if the state `hasFilters` is true.

2021-09-27 22:00 UTC, manuq commented on packages/template-ui/src/App.vue
> +    return Promise.all([channelPromise, filterOptionsPromise, sectionsPromise]);
Same here, only if `hasFilters` is true.

2021-09-27 22:00 UTC, manuq commented on packages/template-ui/src/store/index.js
> +  hasFilters: true,
:+1:

2021-09-28 11:54 UTC, manuq requested changes
Looking better! Still with the Dance channel I'm not getting the filters and I see this in the console: `TypeError: Cannot convert undefined or null to object`

![Captura de pantalla de 2021-09-28 07-46-37](https://user-images.githubusercontent.com/83944/135073184-d1fd04cf-fbc7-455b-b9d0-be63bf652e8f.png)

I see that this is because you are missing this in the `CustomContentRenderer.vue` file:

```
      this.hashi.on(events.CHANNELFILTEROPTIONSREQUESTED, message => {
        this.sendChannelFilterOptions.call(this, message);
      });
```

2021-09-28 12:03 UTC, danigm commented
> I see that this is because you are missing this in the CustomContentRenderer.vue file:

>     this.hashi.on(events.CHANNELFILTEROPTIONSREQUESTED, message => {
>       this.sendChannelFilterOptions.call(this, message);
>     });

Good catch! I had that change on my local clone, but I didn't added to the commit correctly. Now I've fixed the other branch and it should work.

2021-09-29 13:00 UTC, merged