Channels presentation: Add overrides for HarperCollins
endlessm/kolibri-explore-plugin pull request #557
Opened 2023-05-31 18:09 UTC by jprvita

Fixes: https://github.com/endlessm/kolibri-explore-plugin/issues/555

2023-05-31 18:09 UTC, jprvita commented
This is missing the header background asset, as the one provided was too large (> 2000KB).

2023-05-31 20:02 UTC, jprvita commented
I wasn't able to test this yet, but I think the changes are correct and ready.

2023-06-01 11:15 UTC, manuq requested changes

2023-06-01 11:15 UTC, manuq commented on kolibri_explore_plugin/assets/src/customApps.js
> +  '608fd926be60462aba2feccba6c050c9': 'harper-collins',
```suggestion
  '608fd926be60462aba2feccba6c050c9': 'harper-collins.png',
```

2023-06-01 11:15 UTC, manuq commented on kolibri_explore_plugin/assets/src/customApps.js
> +  '608fd926be60462aba2feccba6c050c9': 'harper-collins',
```suggestion
  '608fd926be60462aba2feccba6c050c9': 'harper-collins.png',
```

2023-06-01 11:34 UTC, manuq commented
@jprvita 2 things came up here while testing. I hope you don't mind if I finish this in order to merge and release!
- The references to icon and thumbnail were missing the file extension.
- For a weird reason we need `channel-overrides/harper-collins/styles.scss` to exist even if empty. So if no color overrides were requested we need to add an empty file to revision, otherwise the build fails.

2023-06-01 11:34 UTC, merged