footer: Use Native App Install Prompt to install Android app
endlessm/kolibri-explore-plugin pull request #658
Opened 2023-06-22 13:34 UTC by pwithnall

When supported, use this API to provide a slightly more streamlined experience for installing the Android app when pressing the “Get it on Google Play” button.

The API is only supported by Chrome, on mobile, if the app is advertised as a related application in the PWA manifest for the site, and if the app is not already installed.

The full list of requirements are here:
https://developer.chrome.com/blog/app-install-banners-native/#what-are-the-criteria

If the API is not supported, the button will function as a link as normal.

Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

https://github.com/endlessm/endless-key-content-private/issues/64

2023-06-22 13:35 UTC, pwithnall commented
I haven’t been able to test this as the API is not supported on the desktop, and on my phone I can’t get Chrome to load a locally-hosted version of the site (and can’t figure out why). Hopefully we can test this using the dev instance.

2023-06-22 15:37 UTC, manuq commented
I have added a fixup to satisfy the linter. Done by running `pre-commit run --all-files` locally which runs the code formatters.

2023-06-22 16:05 UTC, manuq requested changes

2023-06-22 16:05 UTC, manuq commented on kolibri_explore_plugin/assets/src/components/AboutFooter.vue
> +    created() {
For better component lifecycle let's move the `addEventListener` to the `mounted` stage, and the `removeEventListener` to the `beforeDestroy` stage. See https://v2.vuejs.org/v2/guide/instance.html#Lifecycle-Diagram

2023-06-22 16:05 UTC, manuq commented on kolibri_explore_plugin/assets/src/components/AboutFooter.vue
> +        deferredInstallPrompt: null,
:+1:

2023-06-23 10:38 UTC, pwithnall commented
Thanks for the helpful review comments. Pushed a couple of fixups for those issues.

2023-06-23 16:15 UTC, merged

2023-06-23 16:16 UTC, manuq commented
Thank you @pwithnall, I used the "squash and merge" from github to merge, I hope that's fine.