Style: Import all font weights
endlessm/kolibri-explore-plugin pull request #850
Opened 2023-09-25 17:28 UTC by manuq

Add a list of all possible weights for each font (Lato, Poppins) and import them.

This should be done with a single import line, but it fails with wrong paths to the font file. So we have to use the SCSS mixin.

Previously only the default font weight (400) was being imported, so text with other weights looked different depending on the web engine used.

Fixes #810

2023-09-25 18:38 UTC, dylanmccall requested changes
Thanks @manuq!

I do have one small nitpick: I don't think we need all these font weights, and these _do_ have an impact on our file size. For two reasons, actually. I'll start on the first one. Searching through our various styles, I think these are the font weights we are using:

- `font-weight: 400` ([`$font-weight-normal`](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L621) from bootstrap)
- `font-weight: 700` ([`$font-weight-bold`](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L624) from bootstrap)
- `font-weight: 600` ([`$font-weight-semibold`](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L623) from bootstrap)

But all of these end up as files under both `kolibri_explore_plugin/static/kolibri_explore_plugin.app` and `kolibri_explore_plugin/loadingScreen/fonts`. The extra .woff and .woff2 files here that _we never use_ account for about 1.6 MB of our final build size. It isn't enormous, so if you feel it's worth the extra bytes to to keep all these fonts around for easier prototyping, that's all good.

Alas, there is also something that is extremely weird about the CSS we generate here. In my `kolibri_explore_plugin.app.6.47.0.css` generated with this change, here's where we specify the source for Poppins with font-weight 400:

```css
@font-face {
    font-display: swap;
    font-family: Poppins;
    font-style: normal;
    font-weight: 400;
    src: url(poppins-devanagari-400-normal-64d5f06ee726edd58ca3.woff2) format("woff2"), url(poppins-all-400-normal-6fbfdac99c274b77fe96.woff) format("woff");
    unicode-range: U+0900-097f, U+1cd0-1cf6, U+1cf8-1cf9, U+200c-200d, U+20a8, U+20b9, U+25cc, U+a830-a839, U+a8e0-a8fb
}

@font-face {
    font-display: swap;
    font-family: Poppins;
    font-style: normal;
    font-weight: 400;
    src: url(data:font/woff2;base64,d09GMgABAAAAABWoAAwAAAAAMsgAABVWAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGx4cLgZgAIIACskovF0LgmQAATYCJAOFRAQgBYNcB4ohG0MqVUaGjQOAOH53UZQHRgv+/5LAyRi/ObhWolrxUM8pbq7lDl3rRIaGgiAuOJCVt0Ps5weIZSHTXFnYxTJyOXIWsxjRm8VPdjMC+mm/iSg3cw9T5rF3h/Q/LWxyjIZGEpPne/b73z4zXzT9n7ESSNa8QhdfHSIvFBqJSqKZpCRakqU7P89v8w9YjRkgKhiElTziEYIgonDBRnsKKFurC/fnMtXpunQV6Y/SZQycc/ubVtFvikI/yMEvertSNMrBPqFgSWdKPvtBspupE/LWZcGtZwoWEC5rrkg8ofMMRdpay2TeJa8YHWGJhDoSwjwLC6QIFmRlhWn8a63cqaEmwFpae/wcl2wTaJtDl7VdeaZ2xOUQP0mfNwmmY8NGswVAXjy6/9NlttLOjIlkH0N3Kbq1i0pFn6YZf4+WRrMsZ9GAOsD1BVDWHmgV0gFXAXw9IrweuWigxjZ9m5SpY87SMtJe35YIYRTHMcIIp923/brZMZRqd9Ezy2y1rC2v8mVQNWKA8SQFwA4ECEDgnpMowRYsAZgRpoXRolls7HNLb2aBxySVnRGQdcdrFqMyjxVAdVURcHnaJMVYwVG3Dm6W54mLV/gyOA7A8QNLv6Vf5VpTmY4BPAEUpQ4CxyrOLwC9+pAFELjVEv7jJ21vjhewDyGxwU4hh5Gk4JEHRZ9JmZsF+VHRUh+ZJr4L+hISErJRPigfUdxbgPz7AwR77JrIJCYlkihTnJpN6/cKLWwX3wZ9JoN/Efr1ZxqGZpuqKLA0iXemlqfL6ifnJfnFgbo9tbNrtAC/3z7rBgKsYluxoe2+Vz9xyoHHYOsFYM8HrHWBOh8vxCSI24QQI6rBhDXpTjSwB8Pi1wrUyl8AtkntDB3K2NtYBQbrlkQoXy9Y1QtEOAiyfJ5mKX+PxurCJpjy0HECDX0HXtmaPpc42DHpBJ/NWvrGSUkZY9ss48EwMdNnWmKWABu08o62HJxsXGytNZ/xRNLKiSZgyniC5hXI61muypywJYr/3/peJqfbKq2+/DByomX03iStAO3mSS8t87tzmu0GvjdByNCT34UypDgZZLGWMJq1xqwi+jh78f0kuoISgnLK4j2S9Rmz893P0/wNs1qzlibtvVHuANOAgd4ZSkCxRv4/KUSt71kbHUQbY0DjbEkZTpEXDyqE1FxUdDNBSckevf6jOf9eSuUjZHGVSV/V5AwwEDhgWw7Mu5i2jQ4Qu2nWxTPmHwmfTYMco6lSnKccsToypoWO4GuRyB0gNLI+I5wYjlC0OpzhA3J82lr95C0QgJTNQM2235Hw65sGZJJFmDEU56hgQ5l4bWJZktJJmeZUBm9rUWCQiHOY8B2wcZovIxnwMECZInJN42n+HRqU170aIfQd5KAumv3mv9Oi5skZq+M8LyxvOO91aInVvGMK2cktUgoBLX0vwSCR/QFQCTi3vjVBnVChGSjHBoEMZFH8ZO1dKIBxQfOJvKYdi/w3BEMJAWyJB5QIE7hu0WJKpN++SR++ZjNmJ6xHoIakp8LTlOsyEv1FOWSiLWka7x8vgkJbJwhZFFvP8wL8n9aBYF6gBoTnQT2Td2QA1+0DCNM+tuFyt6+wefSy/2aGXt4KasTxeEATs+EPpj459Dmxax5SRieJoEFf03dAXQj1BJGQS1PnWUQMmg74XhgycOs7VmfUWrIcsAPGzLGU1PB5YfSei2q2Xb3mS2wr8VnSCopQG7/pe8wy5EDzaRmVZiw6j1hsktHzauaYXZTMQE2p0mAbUijnlhhNpPJRjEk8Ptxj0ZBDHix29lkTcfy1GwRZxxldLIqH9kN12nSCzcdZkZndkwq63NI4sIVEX7DhgzQSGKW3pXs5/uguW4+OlOnUO7mRRb2rlXRSdTqC+U0+C/EFz7gzRJiliTQ+55hXVvs7dMNtQ8hWY/9knD900Qt3gMw60QaKYt4EyFAzdukoAXgP6hB6pyQJsIUWXQcRxtA8rrTbjH1lWmloSVPHB2sdWnEayVj2m1SiuepO2vbpMO8Pqc6UlNyYfNaTZKYPd1s87eRW4ohiv81aqJU9sBlZM9c1Ac8aYEjuKWO4TnYzFXWuvpgou0JHPb4L06SHrv9+nb9UVjPWC+RObNZcKHcj6V56hZebKTdMQHaCNZPBXn7LOikb5f3qwX5h63pdMkRghd02M8lLSbcg0fVY+vPUbcpZKHL/vJDBBxk5AiVPNCxO3a2nkXOdNcHcj9/+b1Y8NMM48fMZ/cTPxLofxPXYPxV03V80I9HhbnbWgeB4CPL+Bl+Yxxk15imdYpyfkSXgSTo9fmVy+8Mi/4yEGLZAE5FabELWiuKM7KTEhJ6IIK7R/ojAl8aKYeBaWqa6UWuZp8tYn8juocKNTm4dnE5bbnquMbRENt3cMlkJFZP0pRVVjRWzjQ3OrpU8jpCkEWIhWAf8tZORtKL0217r696rfGhiSfo3BdpJ1N+DyoybGqmVjVcbMInQhOVMUObnTDBhQkkD52ojtWJTg7GsR4P6qmDpwHplUXd9fdGq9Qrjg8EHnY2z53RMnjO/cxJlEmwY9fdP8c/XAeLRB0eLQfvpciNHKGzhcCYoFJzxLRxh1ZSx9tVeotF8mwI0Z7FCW9ar0fZVVWn7ezVlTZsbqRWwYWAQDcIG4XuRbBCBIdFIo6ODqDGKhiDC2kX6Q+VlGuqrrqb8lspxaQvGmZiv5EwwYSJRpDGuzJfp7L+YEA6vCxgViAZfyBoSElAarmhUuG0nt+s7RUI8IxPHxJ0wVNDAyFDZlmXzOdwcUTY7cleO7ySum4KcKslJSSmsieOWTyizyasUCNMzUgSpCdQdf83lkvIpaRIOO0Fdm4TDl4HB0SbUdEwE6wYGdRq1PE+j1g2igUKe2ZwiEplTuObCAUhbMHhhoKqPsYFRCSdvlC2VbpBW9UqWSSB+4OUuG2Tzapd+S+mWUlguVcqO4/JQqewgDr+v5942yIBWjU0y84R4bUZPpZairdpRlykQtgqwjvxr6UykZLDZ+XFMlJnF1OZLNFHOM3nf02N4Uv3kMg9V+Y28lHRpSV15RUm9NF2W9KrcM39KZYV0DA9rU0G2Hb3fMq9Sg6dJE3+Ue0qnlJdLx/F47QUFWNs4bp50NJZtFuv4MSIplcErLbTO1UDr4DqTHhNDnNVizpE1zNU7Fmpe6NI54mJdgWlHbZZAaLaSK83frUuPbH0HbXg1hIbgUMz4MUZMk6iQqwS4Uq2KQxQk3aSNSYbhogk8fnuBEm+fyJVKJ3LxtoICUXsbT8qQFcTEIw6HjfKjmSxFNFOahjGQ/F0Ox74UsbOLfZavpyEKUsO1ogpaiiS0OJnLTo4/Qqa85bhek4QkZifQmDwUmYaakIUM0V4lMJeH+Ydx/9shDMolxDAFmsg0YJEpSL5cG5ucrY9PrZXkaBLktUaYfw0xwDJSNpOLp+xuXpHiLWTdxEvTL+mmXh5/GShkjzXU4nqbx4H6LYc2HYJ5Iidxq9hujq3IIIKExv+9vIa9PIfZtP89Zz0JPUWY+hV7QfNjbikXfr9728C9PQHohpHv/O8f/PDWlQ6qFRVdgzvwlrkLXy6ATRX45hkeMAuVhfEPphlnL5g8efb8zkn/HFce/3cS5Hx1rE8JEqSyiOjs/MQn5Z7StvISrDnjdJ2s9mZ9Ji9Bzwt30mieBKtJttRL9PzGLkkLN8uM67JjJXmRTLwGWUtrJf9Hyz0zikcH/fr0dB2VLRitD1v+hT2nrxx377LLw/uz/9jW7vIlUudJ0ieGs/kMtqCMXZC7FcqSztYdjnLu1uZ7KlkFXKsouzH1Wph2SFu9ujb4zN+qs8vCU6lsup/a35up0v67oNTOsFCboeOPKQV/ilY2JzbLtfKMYLEVsQ2unCCdG/Pz4EMc0OWY+XYVVOJYVMRxO0IRDeC/4phrMdtqPGWMtKa2ebP8Je8kpZj0NEYyiaHQgPeUaIOeFpfozVAhBbU+e2fO9eN4eDlrAxokCv02y5az/fww7kumUbIv/52/Gn0bCVEeG2wgUxAFMkcHZWSiQYQFc0xp2oJZG2mmSlqc5Q8Evk24++YtGkJ7br5tI7gmYCsiSaQ4rf1nbMnuNqzXUbeYYI1xKaYq36OI/g7uxdFTI1h0X3WAN7NAezPt46IN+rd5tf7eLNWg5DpqKqkPHMRxL/QdByQNaAhtSblEPGvzHnjCRh5fGi8P4MkDs1BQA5WPR3eBN3M7/i1Ifi6D8/0kKHLyppRzOuXhWiTW/lOo6WVj7sWHqS4dAqIa1yXPjZy7Z1cPJHYdrUD8NgwNkPx8d5sTq9Sk/J6ymsdmxGFJiaa0stBXPt6vQlkGnY2pGmSb2uWAu7JEJbNiCb/o1efZ6pEFp5keAmJTBX6sRtemY6L7oqNNEJhM9IjYHVhQDSYQC7pQ11zxXCzSlYblKlxK06DhVfhQMWyab6k7ialCa5/fRiRiXh7rxwCF1wcaajpUpLo6/BBp2XSds2GKYQBt0PuD1/z8PQU5rX4EUQgg85rg3/tL1fl9NbWK1fzvxxWlCyXyhdWBIbFEfkZDdVqO1Cj24tSGVG8aY85srY7PrLTg3uSkVNYkcYG4ux6TmqyFLUkka6E4R+BjLXIPPMxOIvGthQKpnbpGrrcWH0OOSFJkyOml2fb2Y6go4oJ7mwLJ3bMwWbE770cgmLKJZXYbaWkRrBo9OLQNPkLs1J9+zEjhf/VAHt8PX1hYualLiXcpZihwCF8/Q94lx7uUM5QQ0y/CMUyMp7olUpfExS6hJpKAuZXCGkrrPYShbedjYx7ExT2IiT3PEA57ew/7+o6wezLiC97zeZHuW+kPNE5urZR4ecFw2uWAL1H3WB+eALlBBme5PH15umB5Hnx4tLSx/VODtA/jJL2WXt8C3Nj/eNvdo6JSz9e93xytdA8qm+J+ala//ar48s5BnJ20yq1RnM2re/xjzJzjjm1wO6z0ofDhODROJVSVqnCV9IV5nEFTaDaOmyboFOPcjCwBV9IJcII1gE0IN898VfaW27OARd1jt9JjD7KZT40tLEU+aqqtC3rDM59h3F+/vmH/bm/ylW6LkG1rt9N5IkSmhJ1PlCH7SsUfGLQRlRBfz1LT4l4HzASVjzghdrGKfABaKexLo78r/RrX7VGfbOxXHwfkoPRNiZy/vqDvMxhU4XNRQfgnVc9UqKDne74XuyJyzFMp7bq/On1urthJV0oEdAMdiTmFarEo3dYL53DRRTlQ2qhd2RDn2H8jqJ4+rO6PrdLvCHIR1HNGDlpfQL0BDEFbUNd9Wbjm8t5zQgSr/e1sLB3dpoPTuu77yE3pZtJJHai3TQ6RekQ3IOs5rof0wLeqJI0kxNOH1avdV692Tt3vKgQhA3KfvypCy3kolFV+YY+UGRMK86x6NCoUvwlP8C5VJktlXAOCcwOdE2Ti3WdhzDMYS3Zd90URcbWiLTjKm399L/VKoiVFLy8sLD+2qSWAv24pJbilCsUPNileVouw0s7FlvY+HexaiTwUaX+rF+PUcuxsFhmufX8Xff/VTPrfDo6D6mgV+tzLrjM6aQsPy9Wv2vU6dNTbGdc01k3SedsjDqCWdTs7gNpcgxsjp+tI7xpIGxkm5eQmaecjiPzmGctbX8C4nFLt/FUIarWcXufnYjutVdPrzPzXbidWXY/xyRJ40eX18qu693Uz98Piql5bBuBicjsDt/f4KT7rr52iWZeJtJEPZCr/mq9HlW2MGkfVxiA38zy9TtxodHsS7hysj1QKf80Li9M35rQaPp+rXueZqMgZ0kaG8cnGZoqpdM/foebfn3oGR4COqNcwUAndgbk/l1b+2DViQYa799weTU87A5c31k3SzkfK6vzzpXYtyerhtUHuaoMY5Yfcw72N7SzU/j4I5x2A5zUEBLBGKBh3Va8ucUn/Y+sSrQC+rD1xFIDvXomXf/z/47S9jTkA2AQiAALw1n18+39TzZdRBwECrGa+ynvpODzdi7UCuTUeu/qFtiXQ65RuEiC37bUaHxPZCflYmGSRS++NWEoFCqs1xH0dVTh3XFtsCOBWa9G [...]

2023-09-26 01:39 UTC, dylanmccall commented
Okay, figured the woff file thing out to my satisfaction. It isn't really anything we can fix, but I'll report an issue with upstream Kolibri: their base webpack configuration inlines woff and woff2 files when they are below 10 kB, and it just happens that a lot of the fallback font files here are below 10 kB. Which adds up. Other than that, whatever, it's fine.

I did notice one thing, which is if we update the `@fontsource/` dependencies to `^5.0.8`, we can use some shiny new mixins that are a little easier to read:

```scss
@include Lato.faces(
  $weights: (
    400,
    700,
  ),
  $formats: woff2
);

@include Poppins.faces(
  $weights: (
    400,
    600,
    700,
  ),
  $formats: woff2
);
```

2023-09-26 13:12 UTC, manuq commented
@dylanmccall it is really great to only add the specific weights being used. I wasn't sure how to find out since the CSS is split in each component. But I've been testing and your list seems complete! I also verified quickly with `git grep weight`.

Also the SCSS mixin in the v5 version is very handy. I copy-pasted your code and it worked. Thanks! Ready for a second review.

2023-09-26 16:42 UTC, dylanmccall approved these changes
Okay, looks good! :)

2023-09-26 16:42 UTC, merged