Download content pack even when there is content
endlessm/kolibri-explore-plugin pull request #866
Opened 2023-10-03 18:16 UTC by manuq

Change the assumption for showing the welcome screens: before, when there was content in the database it was assumed to be already downloaded and the download was skipped. Now rely on the presence of a DOWNLOAD_COMPLETED state persisted.

Fix #863

2023-10-03 18:47 UTC, jprvita requested changes

2023-10-04 02:06 UTC, dbnicholson approved these changes
Looks good to me if you can clean up the debug message. One of these days I'll learn how all the routing works... It would also be nice to store the download state in the backend database someday.

2023-10-04 11:27 UTC, manuq commented on kolibri_explore_plugin/assets/src/modules/topicsRoot/handlers.js
> +      console.log(['MANUQ', status, shouldResume, grade, name]);
Haha, this was a print leftover.

2023-10-04 12:33 UTC, manuq commented
> Looks good to me if you can clean up the debug message. One of these days I'll learn how all the routing works...

The routing is a pain. I have checked in latest Kolibri and the situation didn't improve. So Kolibri has [a wrapper around vue-router](https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/router.js) which plugins use [passing a routes object](https://github.com/endlessm/kolibri-explore-plugin/blob/24d9254f1e49a9dfb402860adaea705a103fee89/kolibri_explore_plugin/assets/src/app.js#L30). But also Kolibri has a [SET_PAGE_NAME](https://github.com/learningequality/kolibri/blob/a061ef2dac07e8cb3022691b236bc93d186e87c5/kolibri/plugins/coach/assets/src/modules/pluginModule.js#L32) and the current page is used to display a different component in the root view (in our case [in the ExplorePlugin](https://github.com/endlessm/kolibri-explore-plugin/blob/24d9254f1e49a9dfb402860adaea705a103fee89/kolibri_explore_plugin/assets/src/views/ExploreIndex.vue#L9-L15)). And in the same root has [a `<router-view />`](https://github.com/endlessm/kolibri-explore-plugin/blob/24d9254f1e49a9dfb402860adaea705a103fee89/kolibri_explore_plugin/assets/src/views/ExploreIndex.vue#L22). This is kind of redundant. The Vue Router library should take care of mapping routes to components and display them in the router-view directly, as in the very beggining of their getting started guide: https://router.vuejs.org/guide/

> It would also be nice to store the download state in the backend database someday.

Yeah.. that was the idea when implementing content packs management (install more packs, remove packs, etc).

2023-10-04 12:34 UTC, merged