Discovery: Add main buttons
endlessm/kolibri-explore-plugin pull request #93
Opened 2021-06-07 16:05 UTC by danigm

This patch adds five buttons to the discovery page header bar with
predefined search terms, clicking on that button it will open the search
page with that query and will show the results.

https://phabricator.endlessm.com/T31940

2021-06-07 19:12 UTC, manuq requested changes
Looks great, I left some suggestions.

2021-06-07 19:12 UTC, manuq commented on kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
> +          params: { query: event.target.innerHTML.trim() },
Instead of using `innerHTML` you can pass the term as a parameter to the `goToTerm()` handler.

2021-06-08 11:14 UTC, danigm commented on kolibri_explore_plugin/assets/src/views/ChannelsPage.vue
> +        </div>
Yep, a lot better with the data. I've updated the code to do exactly this. Thanks.

2021-06-08 12:36 UTC, manuq approved these changes

2021-06-08 12:36 UTC, merged